import { mkdtemp, mkdir, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { dirname, join, posix } from "node:path";
import { runShellCommandOrThrow } from "../utils/shell.js";

export const hostedFixtureIds = [
  "unsafe_usage",
  "dependency_manifest",
  "accepted_risk_suppression",
  "fixture_diff"
] as const;

export type HostedFixtureId = (typeof hostedFixtureIds)[number];

export interface HostedFixture {
  id: HostedFixtureId;
  title: string;
  description: string;
  files: Record<string, string>;
}

export interface HostedDiffFixture {
  id: "fixture_diff";
  title: string;
  description: string;
  beforeFiles: Record<string, string>;
  afterFiles: Record<string, string>;
}

export const unsafeUsageFixture: HostedFixture = {
  id: "unsafe_usage",
  title: "Unsafe usage demo fixture",
  description: "Small public Rust snippet with unsafe functions, raw pointers, FFI, and unsafe trait impls.",
  files: {
    "src/lib.rs": `pub unsafe fn read_byte(ptr: *const u8) -> u8 {
    unsafe { *ptr }
}

pub struct Shared(*mut u8);

unsafe impl Send for Shared {}
unsafe impl Sync for Shared {}

pub extern "C" fn exported_len(ptr: *const u8, len: usize) -> usize {
    unsafe { std::slice::from_raw_parts(ptr, len).len() }
}

pub fn take_raw(ptr: *mut u8) {
    let _owned = unsafe { Box::from_raw(ptr) };
}
`
  }
};

export const dependencyManifestFixture: HostedFixture = {
  id: "dependency_manifest",
  title: "Dependency manifest demo fixture",
  description: "Public Cargo metadata fixture with git dependencies, path dependencies, build dependencies, and build.rs.",
  files: {
    "Cargo.toml": `[package]
name = "dependency_manifest_demo"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = "1"
demo_git = { git = "https://github.com/example/demo-rust-crate", rev = "0123456789abcdef" }
local_helper = { path = "crates/local_helper" }

[build-dependencies]
cc = "1"
`,
    "Cargo.lock": `# This file is automatically @generated by Cargo.
version = 3

[[package]]
name = "demo_git"
version = "0.1.0"
source = "git+https://github.com/example/demo-rust-crate?rev=0123456789abcdef#0123456789abcdef"
`,
    "build.rs": `use std::process::Command;

fn main() {
    let _ = Command::new("sh").arg("-c").arg("echo building demo").status();
}
`
  }
};

export const acceptedRiskSuppressionFixture: HostedFixture = {
  id: "accepted_risk_suppression",
  title: "Accepted risk suppression demo fixture",
  description: "Public Rust comments demonstrating active, expired, and invalid accepted-risk suppressions.",
  files: {
    "src/lib.rs": `pub fn active_accepted(ptr: *const u8) -> u8 {
    // rust-security-auditor: ignore RSA-UNSAFE-BLOCK owner=@security ticket=SEC-101 until=2099-01-01 -- legacy FFI shim accepted for hosted demo
    unsafe { *ptr }
}

pub fn expired_accepted(ptr: *const u8) -> u8 {
    // rust-security-auditor: ignore RSA-UNSAFE-BLOCK owner=@security ticket=SEC-102 until=2000-01-01 -- old acceptance that should be revisited
    unsafe { *ptr }
}

pub fn invalid_accepted(ptr: *const u8) -> u8 {
    // rust-security-auditor: ignore RSA-UNSAFE-BLOCK owner=
    unsafe { *ptr }
}
`
  }
};

export const fixtureDiffReviewFixture: HostedDiffFixture = {
  id: "fixture_diff",
  title: "Current diff review demo fixture",
  description: "Public git diff fixture that introduces an FFI boundary and raw slice construction.",
  beforeFiles: {
    "Cargo.toml": `[package]
name = "fixture_diff_demo"
version = "0.1.0"
edition = "2021"
`,
    "src/lib.rs": `pub fn checked_len(input: &[u8]) -> usize {
    input.len()
}

pub unsafe fn legacy_read(ptr: *const u8) -> u8 {
    unsafe { *ptr }
}
`
  },
  afterFiles: {
    "src/lib.rs": `pub fn checked_len(input: &[u8]) -> usize {
    input.len()
}

pub unsafe fn legacy_read(ptr: *const u8) -> u8 {
    unsafe { *ptr }
}

pub extern "C" fn exported_len(ptr: *const u8, len: usize) -> usize {
    unsafe { std::slice::from_raw_parts(ptr, len).len() }
}
`
  }
};

const hostedFixtures = new Map<HostedFixtureId, HostedFixture>([
  [unsafeUsageFixture.id, unsafeUsageFixture],
  [dependencyManifestFixture.id, dependencyManifestFixture],
  [acceptedRiskSuppressionFixture.id, acceptedRiskSuppressionFixture]
]);

export function isHostedFixtureId(value: string): value is HostedFixtureId {
  return (hostedFixtureIds as readonly string[]).includes(value);
}

export function getHostedFixture(id: HostedFixtureId): HostedFixture {
  const fixture = hostedFixtures.get(id);
  if (fixture === undefined) {
    throw new Error(`Unsupported hosted fixture: ${id}`);
  }

  return fixture;
}

export async function withHostedDiffFixture<T>(action: (projectPath: string) => Promise<T>): Promise<T> {
  const root = await mkdtemp(join(tmpdir(), "rust-security-auditor-hosted-"));

  try {
    await writeFixtureFiles(root, fixtureDiffReviewFixture.beforeFiles);
    await runShellCommandOrThrow("git", ["init"], { cwd: root });
    await runShellCommandOrThrow("git", ["config", "user.email", "fixture@example.invalid"], { cwd: root });
    await runShellCommandOrThrow("git", ["config", "user.name", "Hosted MCP Fixture"], { cwd: root });
    await runShellCommandOrThrow("git", ["add", "."], { cwd: root });
    await runShellCommandOrThrow("git", ["-c", "commit.gpgsign=false", "commit", "-m", "baseline hosted fixture"], {
      cwd: root
    });
    await writeFixtureFiles(root, fixtureDiffReviewFixture.afterFiles);

    return await action(root);
  } finally {
    await rm(root, { recursive: true, force: true });
  }
}

async function writeFixtureFiles(root: string, files: Record<string, string>): Promise<void> {
  for (const [relativePath, content] of Object.entries(files)) {
    assertSafeFixturePath(relativePath);
    const absolutePath = join(root, relativePath);
    await mkdir(dirname(absolutePath), { recursive: true });
    await writeFile(absolutePath, content, "utf8");
  }
}

function assertSafeFixturePath(relativePath: string): void {
  const normalized = posix.normalize(relativePath.replaceAll("\\", "/"));
  if (normalized === "." || normalized.startsWith("../") || posix.isAbsolute(normalized)) {
    throw new Error(`Unsafe hosted fixture path: ${relativePath}`);
  }
}
